version: '2.4'

services:
  web:
    command: python /app/manage.py runserver 0.0.0.0:3334
    environment:
      DEBUG: ${DEBUG:-True}

  ml_api:
    environment:
      ML_API_CONNECT_TIMEOUT_SECONDS: ${ML_API_CONNECT_TIMEOUT_SECONDS:-0.5}
      ML_API_READ_TIMEOUT_SECONDS: ${ML_API_READ_TIMEOUT_SECONDS:-5}
      ML_API_GCS_CONNECT_TIMEOUT_SECONDS: ${ML_API_GCS_CONNECT_TIMEOUT_SECONDS:-10}
      ML_API_GCS_READ_TIMEOUT_SECONDS: ${ML_API_GCS_READ_TIMEOUT_SECONDS:-30}
    volumes:
      - ./ml_api:/app
    ports:
      - 3333:3333
